In [1]:
from IPython.display import display

In [5]:
from alpaca.data import CryptoHistoricalDataClient

In [6]:
client = CryptoHistoricalDataClient()

In [4]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoLatestQuoteRequest

In [5]:
request_params = CryptoLatestQuoteRequest(symbol_or_symbols="BTC/USD")

latest_quote = client.get_crypto_latest_quote(request_params)

latest_quote["BTC/USD"].ask_price

23049.0

In [3]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

In [2]:
import pandas as pd

In [7]:
request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD", "LTC/USD", "SOL/USD", "DOGE/USD"],
                        timeframe=TimeFrame.Day,
                        start="2020-01-01",
                        end="2022-08-11"
                 )

bars_test = client.get_crypto_bars(request_params).df

In [9]:
bars_test.to_pickle('data_btc_eth_ltc_sol_doge_dayframe.pkl')

In [49]:
bars_test.to_pickle('data_btc_eth_ltc_sol_doge_2y.pkl')

In [42]:
client = CryptoHistoricalDataClient()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Day,
                        start="2022-07-27",
                        end="2022-08-02"
                 )

bars_week = client.get_crypto_bars(request_params).df.close.to_numpy()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Day,
                        start="2022-07-02",
                        end="2022-08-02"
                 )

bars_month = client.get_crypto_bars(request_params).df.close.to_numpy()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Day,
                        start="2021-08-02",
                        end="2022-08-02"
                 )

bars_year = client.get_crypto_bars(request_params).df.close.to_numpy()

In [53]:
request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Day,
                        start="2022-07-18",
                        end="2022-07-25"
                 )

bars_week = client.get_crypto_bars(request_params).df.close.to_numpy()

In [54]:
bars_week.shape, bars_week.std(), bars_week.mean(), bars_week.std()/bars_week.mean()*100

((8,), 698.7464557155191, 22431.125, 3.115075395083925)

In [48]:
bars_month.shape, bars_month.std(), bars_month.mean(), bars_month.std()/bars_month.mean()*100

((32,), 1417.2345637168712, 21625.0625, 6.553666902543617)

In [49]:
bars_year.shape, bars_year.std(), bars_year.mean(), bars_year.std()/bars_year.mean()*100

((366,), 11870.059687289457, 41705.1912568306, 28.461827723533922)

In [46]:
from alpaca.data.live import CryptoDataStream

In [ ]:
stream = CryptoDataStream()
async def quote_data_handler(data):
    print(data)

stream.subscribe_quotes(quote_data_handler, "SPY")
stream.run()

In [1]:
import numpy as np

In [20]:
a = np.array([1,1,1,2,1,1,1,1,1,1,1])

In [21]:
a.std(), a.mean()

(0.28747978728803447, 1.0909090909090908)

In [34]:
a.std()/a.mean()*100

26.352313834736496

In [3]:
import os
os.chdir('C:/Users/Guy/Desktop/NewGridBot/')
display(os.listdir())

['alpaca_key.json',
 'data',
 'indicators.py',
 'output.png',
 'smart_param.py',
 'testing',
 '__pycache__']

In [19]:
import json

In [22]:
with open('alpaca_key.json') as f:
    keys = json.load(f)

In [23]:
keys

{'key_id': 'PK9L4ITHPJSLZZZT2G9W',
 'secret_key': 'LGhF0W83vsacL123NnzGnfCRMp5OLMnRqaIoQFcZ',
 'base_url': 'https://paper-api.alpaca.markets'}

In [24]:
from alpaca.trading.client import TradingClient

# paper=True enables paper trading
trading_client = TradingClient(keys['key_id'], keys['secret_key'], paper=True)

In [25]:
trading_client.get_account()

TradeAccount(id=UUID('f650db5b-b9ef-4f70-9863-47cb235f7d12'), account_number='PA30Z58QKQDU', status=<AccountStatus.ACTIVE: 'ACTIVE'>, crypto_status=<AccountStatus.ACTIVE: 'ACTIVE'>, currency='USD', buying_power='197635.52', regt_buying_power='197635.52', daytrading_buying_power='0', non_marginable_buying_power='98817.76', cash='98817.76', accrued_fees='0', pending_transfer_out=None, pending_transfer_in='0', portfolio_value='98818.1144416', pattern_day_trader=False, trading_blocked=False, transfers_blocked=False, account_blocked=False, created_at=datetime.datetime(2022, 7, 27, 22, 28, 12, 593275, tzinfo=datetime.timezone.utc), trade_suspended_by_user=False, multiplier='2', shorting_enabled=True, equity='98818.1144416', last_equity='98818.11208', long_market_value='0.3544416', short_market_value='0', initial_margin='0', maintenance_margin='0', last_maintenance_margin='0', sma='98817.76', daytrade_count=0)

In [8]:
from alpaca.trading.requests import GetAssetsRequest
from alpaca.trading.enums import AssetClass

In [13]:
search_params = GetAssetsRequest(asset_class=AssetClass.CRYPTO)
assets = trading_client.get_all_assets(search_params)

In [ ]:
assets

In [16]:
from alpaca.trading.requests import MarketOrderRequest, LimitOrderRequest, TakeProfitRequest, StopLossRequest
from alpaca.trading.enums import OrderSide, TimeInForce

In [35]:
market_order_data = MarketOrderRequest(
                    symbol="USD/USDT",
                    qty=1,
                    side=OrderSide.BUY,
                    time_in_force=TimeInForce.GTC
                    )

order = trading_client.submit_order(
                order_data=market_order_data
              )

APIError: {"code":40010001,"message":"could not find asset \"USD/USDT\""}

In [29]:
request_params = CryptoLatestQuoteRequest(symbol_or_symbols="BTC/USD")

latest_quote = client.get_crypto_latest_quote(request_params)

limit_order_data = LimitOrderRequest(
                    symbol="BTC/USD",
                    limit_price=last_price*1.1,
                    qty=0.997,
                    side=OrderSide.SELL,
                    time_in_force=TimeInForce.FOK
                   )

limit_order = trading_client.submit_order(
                order_data=limit_order_data
              )

APIError: {"code":42210000,"message":"limit price increment must be \u003e 1"}

In [18]:
market_order_data = MarketOrderRequest(
                    symbol="BTC/USD",
                    qty=1*0.997,
                    side=OrderSide.SELL,
                    time_in_force=TimeInForce.DAY
                    )

market_order = trading_client.submit_order(
                order_data=market_order_data
               )

In [ ]:
limit_order_data = LimitOrderRequest(
                    symbol="BTC/USD",
                    limit_price=last_price*1.001,
                    qty=1*0.997,
                    side=OrderSide.SELL,
                    time_in_force=TimeInForce.FOK
                   )

limit_order = trading_client.submit_order(
                order_data=limit_order_data
              )

In [62]:
import pandas as pd
import random

In [73]:
df = pd.DataFrame({"values": [random.random()*10000 for _ in range(200000)]})

In [77]:
import numpy as np

In [78]:
arr = np.array([random.random()*10000 for _ in range(200000)])

In [82]:
arr.shape

(200000,)

In [96]:
np.where(arr >= 5000)

(array([     1,      3,      5, ..., 199992, 199993, 199997], dtype=int64),)

In [94]:
arr[(arr >= 5000)]

array([8457.68263026, 9158.16579676, 9125.03210645, ..., 5591.18779436,
       6781.31466351, 7624.10254075])

In [86]:
arr >= 5000

array([False,  True, False, ...,  True, False, False])

In [10]:
import sys

In [14]:
import os

In [17]:
os.chdir('../GridTrading/')

In [19]:
os.listdir()

['alapaca_api.py',
 'alpaca_key.json',
 'indicators.py',
 'main.py',
 'results',
 'result_manager.py',
 'smart_param.py',
 'testgridtrading.ipynb',
 'testing_result_manager.ipynb',
 'testing_smartparam.ipynb',
 'test_api_alapaca.ipynb',
 'trading_bot.py',
 'visualisation.ipynb',
 '__pycache__']

In [1]:
import os

In [5]:
os.chdir('..')

In [6]:
os.listdir()

['alpaca_key.json', 'data', 'testing']

In [9]:
from alpaca.data import CryptoHistoricalDataClient

In [10]:
client = CryptoHistoricalDataClient()

In [7]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

In [26]:
request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD", "LTC/USD"],
                        timeframe=TimeFrame.Minute,
                        start="2021-08-05",
                        end="2022-08-05"
                 )

year_bars = client.get_crypto_bars(request_params).df

In [12]:
import pandas as pd

In [27]:
year_bars

open       high        low      close  \
symbol  timestamp                                                               
BTC/USD 2021-08-05 00:01:00+00:00  39651.000  39651.000  39651.000  39651.000   
        2021-08-05 00:02:00+00:00  39670.000  39720.000  39644.000  39644.000   
        2021-08-05 00:15:00+00:00  39835.000  39835.000  39835.000  39835.000   
        2021-08-05 00:18:00+00:00  39717.000  39717.000  39717.000  39717.000   
        2021-08-05 00:20:00+00:00  39702.000  39702.000  39699.000  39699.000   
...                                      ...        ...        ...        ...   
LTC/USD 2022-08-04 23:51:00+00:00     59.870     59.870     59.870     59.870   
        2022-08-04 23:53:00+00:00     59.840     59.845     59.840     59.845   
        2022-08-04 23:56:00+00:00     59.840     59.840     59.840     59.840   
        2022-08-04 23:59:00+00:00     59.670     59.675     59.645     59.645   
        2022-08-05 00:00:00+00:00     59.645     59.660     59.635     59.660   

                                     volume  trade_count          vwap  
symbol  timestamp                                                       
BTC/USD 2021-08-05 00:01:00+00:00    0.0034          1.0  39651.000000  
        2021-08-05 00:02:00+00:00    0.3091          3.0  39666.878033  
        2021-08-05 00:15:00+00:00    0.0503          1.0  39835.000000  
        2021-08-05 00:18:00+00:00    0.0074          1.0  39717.000000  
        2021-08-05 00:20:00+00:00    0.2879          2.0  39699.525182  
...                                     ...          ...           ...  
LTC/USD 2022-08-04 23:51:00+00:00    2.0000          1.0     59.870000  
        2022-08-04 23:53:00+00:00   67.9700          2.0     59.841148  
        2022-08-04 23:56:00+00:00   14.7300          3.0     59.840000  
        2022-08-04 23:59:00+00:00  100.4800          8.0     59.665634  
        2022-08-05 00:00:00+00:00  207.6700          7.0     59.638443  

[877521 rows x 7 columns]

In [28]:
os.listdir()

['alpaca_key.json', 'data', 'testing']